name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: ./gradlew home:test
      - name: jacoco
        run: ./gradlew home:jacocoTestReportRelease
      - name: coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        run: ./gradlew home:lint
  assembleDebug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: assembleDebug
        run: ./gradlew assembleDebug
